import { google } from "@ai-sdk/google";
import { generateText } from "ai";

/**
 * 1-2 sentence TLDR generated by Google Gemini 2.0 Flash. Free tier
 * gives us 1,500 requests/day — comfortably above our daily ingest.
 *
 * Failure modes are all caught and resolved to `null`:
 *  - Missing GOOGLE_GENERATIVE_AI_API_KEY → no calls made, never fails.
 *  - Rate limit / API error → null so the cron run still finishes.
 *  - Trivial-or-empty input (title shorter than ~12 chars, no excerpt) →
 *    skip the call entirely.
 *
 * The card UI just falls back to the existing excerpt when summary is
 * null, so AI being offline degrades to the previous behaviour rather
 * than breaking anything.
 */

const MODEL = "gemini-2.0-flash-lite";
const MAX_OUTPUT_CHARS = 220;

export async function generateSummary(
  title: string,
  excerpt: string | null,
): Promise<string | null> {
  if (!process.env.GOOGLE_GENERATIVE_AI_API_KEY) return null;
  if (!title || title.length < 12) return null;
  const body = (excerpt ?? "").trim();
  if (body.length < 40) {
    // Excerpt too thin to be worth summarizing — skip to keep tokens
    // for items where AI actually adds value.
    return null;
  }

  try {
    const { text } = await generateText({
      model: google(MODEL),
      // Aggressively low — we want crisp, not creative.
      temperature: 0.2,
      maxOutputTokens: 120,
      // System prompt steers toward the "scanning the feed" use-case.
      system:
        "You write extremely terse TLDR summaries for a developer-focused " +
        "news aggregator. Output 1-2 short sentences (under 200 chars total) " +
        "that capture the most useful fact for someone deciding whether to " +
        "click. No preamble, no quotes, no markdown, no emojis. Plain text only.",
      prompt: `Title: ${title}\n\nExcerpt:\n${body.slice(0, 1200)}`,
    });
    const out = text.trim().replace(/^["'`]+|["'`]+$/g, "");
    if (!out) return null;
    return out.length > MAX_OUTPUT_CHARS
      ? out.slice(0, MAX_OUTPUT_CHARS - 1).trimEnd() + "…"
      : out;
  } catch {
    // Quota hit, network blip, model 5xx — fall back silently. The
    // next cron run will retry rows still missing a summary because
    // we only generate for rows where summary IS NULL.
    return null;
  }
}
